[Fri Jun 22 02:51:32.310200 2018] [ssl:warn] [pid 6776:tid 276] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:51:32.406200 2018] [ssl:warn] [pid 6776:tid 276] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:51:32.494200 2018] [mpm_winnt:notice] [pid 6776:tid 276] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 02:51:32.494200 2018] [mpm_winnt:notice] [pid 6776:tid 276] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 02:51:32.494200 2018] [core:notice] [pid 6776:tid 276] AH00094: Command line: 'C:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 02:51:32.495200 2018] [mpm_winnt:notice] [pid 6776:tid 276] AH00418: Parent: Created child process 6292
[Fri Jun 22 02:51:32.841200 2018] [ssl:warn] [pid 6292:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:51:32.918200 2018] [ssl:warn] [pid 6292:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:51:32.945200 2018] [mpm_winnt:notice] [pid 6292:tid 288] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 02:53:30.863200 2018] [ssl:warn] [pid 4500:tid 284] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:53:30.991200 2018] [ssl:warn] [pid 4500:tid 284] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:53:31.016200 2018] [mpm_winnt:notice] [pid 4500:tid 284] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 02:53:31.016200 2018] [mpm_winnt:notice] [pid 4500:tid 284] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 02:53:31.016200 2018] [core:notice] [pid 4500:tid 284] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 02:53:31.018200 2018] [mpm_winnt:notice] [pid 4500:tid 284] AH00418: Parent: Created child process 4868
[Fri Jun 22 02:53:31.403200 2018] [ssl:warn] [pid 4868:tid 296] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:53:31.488200 2018] [ssl:warn] [pid 4868:tid 296] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 02:53:31.514200 2018] [mpm_winnt:notice] [pid 4868:tid 296] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 03:10:02.854200 2018] [ssl:warn] [pid 6240:tid 284] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 03:10:03.107200 2018] [core:warn] [pid 6240:tid 284] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 03:10:03.121200 2018] [ssl:warn] [pid 6240:tid 284] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 03:10:03.149200 2018] [mpm_winnt:notice] [pid 6240:tid 284] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 03:10:03.149200 2018] [mpm_winnt:notice] [pid 6240:tid 284] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 03:10:03.149200 2018] [core:notice] [pid 6240:tid 284] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 03:10:03.151200 2018] [mpm_winnt:notice] [pid 6240:tid 284] AH00418: Parent: Created child process 3356
[Fri Jun 22 03:10:03.529200 2018] [ssl:warn] [pid 3356:tid 296] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 03:10:03.589200 2018] [ssl:warn] [pid 3356:tid 296] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 03:10:03.617200 2018] [mpm_winnt:notice] [pid 3356:tid 296] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 14:43:46.641001 2018] [ssl:warn] [pid 5644:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 14:43:46.775001 2018] [core:warn] [pid 5644:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 14:43:46.779001 2018] [ssl:warn] [pid 5644:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 14:43:48.326001 2018] [mpm_winnt:notice] [pid 5644:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 14:43:48.326001 2018] [mpm_winnt:notice] [pid 5644:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 14:43:48.326001 2018] [core:notice] [pid 5644:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 14:43:48.328001 2018] [mpm_winnt:notice] [pid 5644:tid 416] AH00418: Parent: Created child process 3836
[Fri Jun 22 14:43:48.648001 2018] [ssl:warn] [pid 3836:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 14:43:48.710001 2018] [ssl:warn] [pid 3836:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 14:43:48.748001 2018] [mpm_winnt:notice] [pid 3836:tid 288] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 21:37:33.098607 2018] [ssl:warn] [pid 4904:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:37:33.196607 2018] [core:warn] [pid 4904:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 21:37:33.200607 2018] [ssl:warn] [pid 4904:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:37:33.227607 2018] [mpm_winnt:notice] [pid 4904:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 21:37:33.227607 2018] [mpm_winnt:notice] [pid 4904:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 21:37:33.227607 2018] [core:notice] [pid 4904:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 21:37:33.229607 2018] [mpm_winnt:notice] [pid 4904:tid 416] AH00418: Parent: Created child process 4108
[Fri Jun 22 21:37:33.675607 2018] [ssl:warn] [pid 4108:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:37:33.808607 2018] [ssl:warn] [pid 4108:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:37:33.837607 2018] [mpm_winnt:notice] [pid 4108:tid 288] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 21:39:30.128607 2018] [php7:error] [pid 4108:tid 1576] [client ::1:2654] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:39:30.132607 2018] [php7:error] [pid 4108:tid 1576] [client ::1:2654] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:43:36.985607 2018] [php7:error] [pid 4108:tid 1576] [client ::1:2770] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:43:36.989607 2018] [php7:error] [pid 4108:tid 1576] [client ::1:2770] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:43:39.872607 2018] [php7:error] [pid 4108:tid 1576] [client ::1:2770] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:43:39.876607 2018] [php7:error] [pid 4108:tid 1576] [client ::1:2770] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:44:38.061607 2018] [php7:error] [pid 4108:tid 1548] [client ::1:2854] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:44:38.065607 2018] [php7:error] [pid 4108:tid 1548] [client ::1:2854] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:45:28.500607 2018] [php7:error] [pid 4108:tid 1568] [client ::1:2863] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:45:28.504607 2018] [php7:error] [pid 4108:tid 1568] [client ::1:2863] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:45:29.218607 2018] [php7:error] [pid 4108:tid 1568] [client ::1:2863] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:45:29.221607 2018] [php7:error] [pid 4108:tid 1568] [client ::1:2863] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:47:17.143607 2018] [php7:error] [pid 4108:tid 1560] [client ::1:2881] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:47:17.147607 2018] [php7:error] [pid 4108:tid 1560] [client ::1:2881] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:47:18.213607 2018] [php7:error] [pid 4108:tid 1560] [client ::1:2881] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:47:18.217607 2018] [php7:error] [pid 4108:tid 1560] [client ::1:2881] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:47:26.798607 2018] [php7:error] [pid 4108:tid 1536] [client ::1:2882] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:47:26.802607 2018] [php7:error] [pid 4108:tid 1536] [client ::1:2882] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:48:06.111607 2018] [ssl:warn] [pid 4884:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:48:06.247607 2018] [core:warn] [pid 4884:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 21:48:06.251607 2018] [ssl:warn] [pid 4884:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:48:06.279607 2018] [mpm_winnt:notice] [pid 4884:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 21:48:06.279607 2018] [mpm_winnt:notice] [pid 4884:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 21:48:06.279607 2018] [core:notice] [pid 4884:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 21:48:06.280607 2018] [mpm_winnt:notice] [pid 4884:tid 416] AH00418: Parent: Created child process 4500
[Fri Jun 22 21:48:06.688607 2018] [ssl:warn] [pid 4500:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:48:06.772607 2018] [ssl:warn] [pid 4500:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:48:06.800607 2018] [mpm_winnt:notice] [pid 4500:tid 288] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 21:48:35.604607 2018] [php7:error] [pid 4500:tid 1556] [client ::1:2898] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:48:35.608607 2018] [php7:error] [pid 4500:tid 1556] [client ::1:2898] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:50:03.462607 2018] [ssl:warn] [pid 1084:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:50:03.535607 2018] [core:warn] [pid 1084:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 21:50:03.539607 2018] [ssl:warn] [pid 1084:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:50:03.569607 2018] [mpm_winnt:notice] [pid 1084:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 21:50:03.569607 2018] [mpm_winnt:notice] [pid 1084:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 21:50:03.569607 2018] [core:notice] [pid 1084:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 21:50:03.570607 2018] [mpm_winnt:notice] [pid 1084:tid 416] AH00418: Parent: Created child process 872
[Fri Jun 22 21:50:03.981607 2018] [ssl:warn] [pid 872:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:50:04.052607 2018] [ssl:warn] [pid 872:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:50:04.086607 2018] [mpm_winnt:notice] [pid 872:tid 288] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 21:52:22.325607 2018] [ssl:warn] [pid 5140:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:52:22.468607 2018] [core:warn] [pid 5140:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 21:52:22.471607 2018] [ssl:warn] [pid 5140:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:52:22.500607 2018] [mpm_winnt:notice] [pid 5140:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 21:52:22.500607 2018] [mpm_winnt:notice] [pid 5140:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 21:52:22.500607 2018] [core:notice] [pid 5140:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 21:52:22.502607 2018] [mpm_winnt:notice] [pid 5140:tid 416] AH00418: Parent: Created child process 4176
[Fri Jun 22 21:52:22.938607 2018] [ssl:warn] [pid 4176:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:52:23.024607 2018] [ssl:warn] [pid 4176:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 21:52:23.050607 2018] [mpm_winnt:notice] [pid 4176:tid 288] AH00354: Child: Starting 150 worker threads.
[Fri Jun 22 21:52:33.053607 2018] [php7:error] [pid 4176:tid 1572] [client ::1:2903] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:52:33.058607 2018] [php7:error] [pid 4176:tid 1572] [client ::1:2903] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 21:53:04.164607 2018] [php7:error] [pid 4176:tid 1552] [client ::1:2907] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\Object.php on line 30
[Fri Jun 22 21:53:04.168607 2018] [php7:error] [pid 4176:tid 1552] [client ::1:2907] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\cakephp\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Fri Jun 22 22:58:13.823607 2018] [ssl:warn] [pid 3708:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 22:58:13.921607 2018] [core:warn] [pid 3708:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Jun 22 22:58:13.924607 2018] [ssl:warn] [pid 3708:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 22:58:13.955607 2018] [mpm_winnt:notice] [pid 3708:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Fri Jun 22 22:58:13.955607 2018] [mpm_winnt:notice] [pid 3708:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Fri Jun 22 22:58:13.955607 2018] [core:notice] [pid 3708:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Jun 22 22:58:13.957607 2018] [mpm_winnt:notice] [pid 3708:tid 416] AH00418: Parent: Created child process 1744
[Fri Jun 22 22:58:14.333607 2018] [ssl:warn] [pid 1744:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 22:58:14.399607 2018] [ssl:warn] [pid 1744:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Jun 22 22:58:14.425607 2018] [mpm_winnt:notice] [pid 1744:tid 288] AH00354: Child: Starting 150 worker threads.
[Sat Jun 23 00:01:31.436600 2018] [ssl:warn] [pid 3612:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:01:32.123000 2018] [core:warn] [pid 3612:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Jun 23 00:01:32.123000 2018] [ssl:warn] [pid 3612:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:01:36.600200 2018] [mpm_winnt:notice] [pid 3612:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Sat Jun 23 00:01:36.600200 2018] [mpm_winnt:notice] [pid 3612:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Sat Jun 23 00:01:36.600200 2018] [core:notice] [pid 3612:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Sat Jun 23 00:01:36.600200 2018] [mpm_winnt:notice] [pid 3612:tid 416] AH00418: Parent: Created child process 1396
[Sat Jun 23 00:01:37.333400 2018] [ssl:warn] [pid 1396:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:01:37.520600 2018] [ssl:warn] [pid 1396:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:01:37.551800 2018] [mpm_winnt:notice] [pid 1396:tid 288] AH00354: Child: Starting 150 worker threads.
[Sat Jun 23 00:02:17.954001 2018] [ssl:warn] [pid 2924:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:02:18.047001 2018] [core:warn] [pid 2924:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Jun 23 00:02:18.050001 2018] [ssl:warn] [pid 2924:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:02:18.077001 2018] [mpm_winnt:notice] [pid 2924:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Sat Jun 23 00:02:18.077001 2018] [mpm_winnt:notice] [pid 2924:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Sat Jun 23 00:02:18.077001 2018] [core:notice] [pid 2924:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Sat Jun 23 00:02:18.079001 2018] [mpm_winnt:notice] [pid 2924:tid 416] AH00418: Parent: Created child process 3800
[Sat Jun 23 00:02:18.449001 2018] [ssl:warn] [pid 3800:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:02:18.623001 2018] [ssl:warn] [pid 3800:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 00:02:18.649001 2018] [mpm_winnt:notice] [pid 3800:tid 288] AH00354: Child: Starting 150 worker threads.
[Sat Jun 23 11:12:39.065000 2018] [ssl:warn] [pid 4708:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 11:12:39.299000 2018] [core:warn] [pid 4708:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sat Jun 23 11:12:39.302000 2018] [ssl:warn] [pid 4708:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 11:12:42.375000 2018] [mpm_winnt:notice] [pid 4708:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Sat Jun 23 11:12:42.375000 2018] [mpm_winnt:notice] [pid 4708:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Sat Jun 23 11:12:42.375000 2018] [core:notice] [pid 4708:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Sat Jun 23 11:12:42.377000 2018] [mpm_winnt:notice] [pid 4708:tid 416] AH00418: Parent: Created child process 1584
[Sat Jun 23 11:12:42.745000 2018] [ssl:warn] [pid 1584:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 11:12:42.808000 2018] [ssl:warn] [pid 1584:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sat Jun 23 11:12:42.835000 2018] [mpm_winnt:notice] [pid 1584:tid 288] AH00354: Child: Starting 150 worker threads.
[Sun Jun 24 01:32:38.247200 2018] [ssl:warn] [pid 4976:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 01:32:38.409200 2018] [core:warn] [pid 4976:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sun Jun 24 01:32:38.412200 2018] [ssl:warn] [pid 4976:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 01:32:38.443200 2018] [mpm_winnt:notice] [pid 4976:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Sun Jun 24 01:32:38.443200 2018] [mpm_winnt:notice] [pid 4976:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Sun Jun 24 01:32:38.443200 2018] [core:notice] [pid 4976:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Sun Jun 24 01:32:38.444200 2018] [mpm_winnt:notice] [pid 4976:tid 416] AH00418: Parent: Created child process 3888
[Sun Jun 24 01:32:38.829200 2018] [ssl:warn] [pid 3888:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 01:32:38.918200 2018] [ssl:warn] [pid 3888:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 01:32:38.945200 2018] [mpm_winnt:notice] [pid 3888:tid 288] AH00354: Child: Starting 150 worker threads.
[Sun Jun 24 02:10:54.232200 2018] [php7:error] [pid 3888:tid 1576] [client ::1:7785] PHP Fatal error:  Cannot redeclare AdminsController::$layout in C:\\xampp\\htdocs\\cakephp\\app\\Controller\\AdminsController.php on line 5
[Sun Jun 24 22:28:38.214000 2018] [ssl:warn] [pid 4960:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 22:28:38.471000 2018] [core:warn] [pid 4960:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Sun Jun 24 22:28:38.474000 2018] [ssl:warn] [pid 4960:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 22:28:42.199000 2018] [mpm_winnt:notice] [pid 4960:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Sun Jun 24 22:28:42.200000 2018] [mpm_winnt:notice] [pid 4960:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Sun Jun 24 22:28:42.200000 2018] [core:notice] [pid 4960:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Sun Jun 24 22:28:42.201000 2018] [mpm_winnt:notice] [pid 4960:tid 416] AH00418: Parent: Created child process 1644
[Sun Jun 24 22:28:42.587000 2018] [ssl:warn] [pid 1644:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 22:28:42.668000 2018] [ssl:warn] [pid 1644:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Sun Jun 24 22:28:42.695000 2018] [mpm_winnt:notice] [pid 1644:tid 288] AH00354: Child: Starting 150 worker threads.
[Mon Jun 25 06:54:38.916000 2018] [ssl:warn] [pid 2696:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 06:54:39.140000 2018] [core:warn] [pid 2696:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jun 25 06:54:39.144000 2018] [ssl:warn] [pid 2696:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 06:54:42.340000 2018] [mpm_winnt:notice] [pid 2696:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Mon Jun 25 06:54:42.340000 2018] [mpm_winnt:notice] [pid 2696:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Mon Jun 25 06:54:42.340000 2018] [core:notice] [pid 2696:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Jun 25 06:54:42.341000 2018] [mpm_winnt:notice] [pid 2696:tid 416] AH00418: Parent: Created child process 456
[Mon Jun 25 06:54:42.762000 2018] [ssl:warn] [pid 456:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 06:54:42.828000 2018] [ssl:warn] [pid 456:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 06:54:42.858000 2018] [mpm_winnt:notice] [pid 456:tid 288] AH00354: Child: Starting 150 worker threads.
[Mon Jun 25 07:22:26.408400 2018] [core:error] [pid 456:tid 1568] (20024)The given path is misformatted or contained invalid characters: [client ::1:1215] AH00127: Cannot map GET /cakephp/front-end/css/style%3Acss.css HTTP/1.1 to file, referer: http://localhost/cakephp/fronts/index
[Mon Jun 25 07:22:27.659400 2018] [core:error] [pid 456:tid 1568] (20024)The given path is misformatted or contained invalid characters: [client ::1:1215] AH00127: Cannot map GET /cakephp/front-end/css/style%3Acss.css HTTP/1.1 to file, referer: http://localhost/cakephp/fronts/index
[Mon Jun 25 10:07:02.270800 2018] [ssl:warn] [pid 5360:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:07:02.367800 2018] [core:warn] [pid 5360:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jun 25 10:07:02.370800 2018] [ssl:warn] [pid 5360:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:07:02.400800 2018] [mpm_winnt:notice] [pid 5360:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Mon Jun 25 10:07:02.400800 2018] [mpm_winnt:notice] [pid 5360:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Mon Jun 25 10:07:02.400800 2018] [core:notice] [pid 5360:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Jun 25 10:07:02.402800 2018] [mpm_winnt:notice] [pid 5360:tid 416] AH00418: Parent: Created child process 4740
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Mon Jun 25 10:07:02.757800 2018] [ssl:warn] [pid 4740:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:07:02.822800 2018] [ssl:warn] [pid 4740:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:07:02.849800 2018] [mpm_winnt:notice] [pid 4740:tid 288] AH00354: Child: Starting 150 worker threads.
[Mon Jun 25 10:08:37.022800 2018] [ssl:warn] [pid 4708:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:08:37.162800 2018] [core:warn] [pid 4708:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jun 25 10:08:37.166800 2018] [ssl:warn] [pid 4708:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:08:37.195800 2018] [mpm_winnt:notice] [pid 4708:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Mon Jun 25 10:08:37.195800 2018] [mpm_winnt:notice] [pid 4708:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Mon Jun 25 10:08:37.195800 2018] [core:notice] [pid 4708:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Jun 25 10:08:37.197800 2018] [mpm_winnt:notice] [pid 4708:tid 416] AH00418: Parent: Created child process 5332
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Mon Jun 25 10:08:37.608800 2018] [ssl:warn] [pid 5332:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:08:37.669800 2018] [ssl:warn] [pid 5332:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:08:37.696800 2018] [mpm_winnt:notice] [pid 5332:tid 288] AH00354: Child: Starting 150 worker threads.
[Mon Jun 25 10:14:53.727800 2018] [ssl:warn] [pid 5104:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:53.873800 2018] [core:warn] [pid 5104:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jun 25 10:14:53.877800 2018] [ssl:warn] [pid 5104:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:53.906800 2018] [mpm_winnt:notice] [pid 5104:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Mon Jun 25 10:14:53.907800 2018] [mpm_winnt:notice] [pid 5104:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Mon Jun 25 10:14:53.907800 2018] [core:notice] [pid 5104:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Jun 25 10:14:53.908800 2018] [mpm_winnt:notice] [pid 5104:tid 416] AH00418: Parent: Created child process 3416
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Mon Jun 25 10:14:54.353800 2018] [ssl:warn] [pid 3416:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:54.463800 2018] [ssl:warn] [pid 3416:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:54.490800 2018] [mpm_winnt:notice] [pid 3416:tid 288] AH00354: Child: Starting 150 worker threads.
[Mon Jun 25 10:14:58.461800 2018] [ssl:warn] [pid 3116:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:58.600800 2018] [core:warn] [pid 3116:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jun 25 10:14:58.603800 2018] [ssl:warn] [pid 3116:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:58.634800 2018] [mpm_winnt:notice] [pid 3116:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Mon Jun 25 10:14:58.634800 2018] [mpm_winnt:notice] [pid 3116:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Mon Jun 25 10:14:58.634800 2018] [core:notice] [pid 3116:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Jun 25 10:14:58.636800 2018] [mpm_winnt:notice] [pid 3116:tid 416] AH00418: Parent: Created child process 2572
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Mon Jun 25 10:14:59.012800 2018] [ssl:warn] [pid 2572:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:59.075800 2018] [ssl:warn] [pid 2572:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Jun 25 10:14:59.105800 2018] [mpm_winnt:notice] [pid 2572:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 18:14:28.203000 2018] [ssl:warn] [pid 1952:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 18:14:28.436000 2018] [core:warn] [pid 1952:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 18:14:28.440000 2018] [ssl:warn] [pid 1952:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 18:14:30.275600 2018] [mpm_winnt:notice] [pid 1952:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 18:14:30.275600 2018] [mpm_winnt:notice] [pid 1952:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 18:14:30.275600 2018] [core:notice] [pid 1952:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 18:14:30.277600 2018] [mpm_winnt:notice] [pid 1952:tid 416] AH00418: Parent: Created child process 2136
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 18:14:30.722600 2018] [ssl:warn] [pid 2136:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 18:14:30.815600 2018] [ssl:warn] [pid 2136:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 18:14:30.844600 2018] [mpm_winnt:notice] [pid 2136:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 20:20:25.241800 2018] [ssl:warn] [pid 3996:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:20:25.365800 2018] [core:warn] [pid 3996:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 20:20:25.368800 2018] [ssl:warn] [pid 3996:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:20:25.396800 2018] [mpm_winnt:notice] [pid 3996:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 20:20:25.396800 2018] [mpm_winnt:notice] [pid 3996:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 20:20:25.396800 2018] [core:notice] [pid 3996:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 20:20:25.397800 2018] [mpm_winnt:notice] [pid 3996:tid 416] AH00418: Parent: Created child process 2108
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 20:20:25.870800 2018] [ssl:warn] [pid 2108:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:20:25.980800 2018] [ssl:warn] [pid 2108:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:20:26.008800 2018] [mpm_winnt:notice] [pid 2108:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 20:25:13.041400 2018] [ssl:warn] [pid 3364:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:25:13.121400 2018] [core:warn] [pid 3364:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 20:25:13.125400 2018] [ssl:warn] [pid 3364:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:25:13.152400 2018] [mpm_winnt:notice] [pid 3364:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 20:25:13.152400 2018] [mpm_winnt:notice] [pid 3364:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 20:25:13.152400 2018] [core:notice] [pid 3364:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 20:25:13.154400 2018] [mpm_winnt:notice] [pid 3364:tid 416] AH00418: Parent: Created child process 5288
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 20:25:13.499400 2018] [ssl:warn] [pid 5288:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:25:13.567400 2018] [ssl:warn] [pid 5288:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:25:13.592400 2018] [mpm_winnt:notice] [pid 5288:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 20:29:36.377400 2018] [ssl:warn] [pid 4072:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:29:36.518400 2018] [core:warn] [pid 4072:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 20:29:36.521400 2018] [ssl:warn] [pid 4072:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:29:36.548400 2018] [mpm_winnt:notice] [pid 4072:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 20:29:36.548400 2018] [mpm_winnt:notice] [pid 4072:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 20:29:36.548400 2018] [core:notice] [pid 4072:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 20:29:36.550400 2018] [mpm_winnt:notice] [pid 4072:tid 416] AH00418: Parent: Created child process 4308
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 20:29:36.953400 2018] [ssl:warn] [pid 4308:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:29:37.043400 2018] [ssl:warn] [pid 4308:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:29:37.069400 2018] [mpm_winnt:notice] [pid 4308:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 20:48:36.506200 2018] [ssl:warn] [pid 2952:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:48:36.640200 2018] [core:warn] [pid 2952:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 20:48:36.644200 2018] [ssl:warn] [pid 2952:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:48:36.671200 2018] [mpm_winnt:notice] [pid 2952:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 20:48:36.671200 2018] [mpm_winnt:notice] [pid 2952:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 20:48:36.671200 2018] [core:notice] [pid 2952:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 20:48:36.673200 2018] [mpm_winnt:notice] [pid 2952:tid 416] AH00418: Parent: Created child process 5788
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 20:48:37.053200 2018] [ssl:warn] [pid 5788:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:48:37.137200 2018] [ssl:warn] [pid 5788:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 20:48:37.164200 2018] [mpm_winnt:notice] [pid 5788:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:00:01.396200 2018] [ssl:warn] [pid 3664:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:00:01.494200 2018] [core:warn] [pid 3664:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 21:00:01.497200 2018] [ssl:warn] [pid 3664:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:00:01.525200 2018] [mpm_winnt:notice] [pid 3664:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 21:00:01.525200 2018] [mpm_winnt:notice] [pid 3664:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 21:00:01.525200 2018] [core:notice] [pid 3664:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 21:00:01.527200 2018] [mpm_winnt:notice] [pid 3664:tid 416] AH00418: Parent: Created child process 5292
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 21:00:01.939200 2018] [ssl:warn] [pid 5292:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:00:02.013200 2018] [ssl:warn] [pid 5292:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:00:02.040200 2018] [mpm_winnt:notice] [pid 5292:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:14:21.491000 2018] [ssl:warn] [pid 2700:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:14:21.585000 2018] [core:warn] [pid 2700:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 21:14:21.588000 2018] [ssl:warn] [pid 2700:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:14:21.616000 2018] [mpm_winnt:notice] [pid 2700:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 21:14:21.616000 2018] [mpm_winnt:notice] [pid 2700:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 21:14:21.616000 2018] [core:notice] [pid 2700:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 21:14:21.617000 2018] [mpm_winnt:notice] [pid 2700:tid 416] AH00418: Parent: Created child process 5060
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 21:14:22.031000 2018] [ssl:warn] [pid 5060:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:14:22.148000 2018] [ssl:warn] [pid 5060:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:14:22.174000 2018] [mpm_winnt:notice] [pid 5060:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:15:49.199000 2018] [ssl:warn] [pid 2332:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:15:49.332000 2018] [core:warn] [pid 2332:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 21:15:49.336000 2018] [ssl:warn] [pid 2332:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:15:49.365000 2018] [mpm_winnt:notice] [pid 2332:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 21:15:49.365000 2018] [mpm_winnt:notice] [pid 2332:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 21:15:49.365000 2018] [core:notice] [pid 2332:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 21:15:49.366000 2018] [mpm_winnt:notice] [pid 2332:tid 416] AH00418: Parent: Created child process 4788
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 21:15:49.734000 2018] [ssl:warn] [pid 4788:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:15:49.833000 2018] [ssl:warn] [pid 4788:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:15:49.860000 2018] [mpm_winnt:notice] [pid 4788:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:18:44.352401 2018] [ssl:warn] [pid 3208:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:18:44.481401 2018] [core:warn] [pid 3208:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 21:18:44.484401 2018] [ssl:warn] [pid 3208:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:18:44.511401 2018] [mpm_winnt:notice] [pid 3208:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 21:18:44.511401 2018] [mpm_winnt:notice] [pid 3208:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 21:18:44.511401 2018] [core:notice] [pid 3208:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 21:18:44.513401 2018] [mpm_winnt:notice] [pid 3208:tid 416] AH00418: Parent: Created child process 4052
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 21:18:44.960401 2018] [ssl:warn] [pid 4052:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:18:45.054401 2018] [ssl:warn] [pid 4052:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:18:45.081401 2018] [mpm_winnt:notice] [pid 4052:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:19:49.949401 2018] [php7:error] [pid 4052:tid 1572] [client 127.0.0.1:4992] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:19:49.954401 2018] [php7:error] [pid 4052:tid 1572] [client 127.0.0.1:4992] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:20:36.858401 2018] [php7:error] [pid 4052:tid 1568] [client ::1:4994] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:20:36.864401 2018] [php7:error] [pid 4052:tid 1568] [client ::1:4994] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:23:26.003401 2018] [php7:error] [pid 4052:tid 1544] [client ::1:5000] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:23:26.007401 2018] [php7:error] [pid 4052:tid 1544] [client ::1:5000] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:23:27.547401 2018] [php7:error] [pid 4052:tid 1544] [client ::1:5000] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:23:27.551401 2018] [php7:error] [pid 4052:tid 1544] [client ::1:5000] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:23:44.505401 2018] [php7:error] [pid 4052:tid 1536] [client ::1:5005] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:23:44.510401 2018] [php7:error] [pid 4052:tid 1536] [client ::1:5005] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:23:45.395401 2018] [php7:error] [pid 4052:tid 1536] [client ::1:5005] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:23:45.399401 2018] [php7:error] [pid 4052:tid 1536] [client ::1:5005] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:23:49.099401 2018] [php7:error] [pid 4052:tid 1544] [client 127.0.0.1:5009] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:23:49.103401 2018] [php7:error] [pid 4052:tid 1544] [client 127.0.0.1:5009] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:26:27.704401 2018] [php7:error] [pid 4052:tid 1560] [client ::1:5013] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:26:27.709401 2018] [php7:error] [pid 4052:tid 1560] [client ::1:5013] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:26:34.443401 2018] [ssl:warn] [pid 2940:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:26:34.611401 2018] [core:warn] [pid 2940:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 21:26:34.614401 2018] [ssl:warn] [pid 2940:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:26:34.642401 2018] [mpm_winnt:notice] [pid 2940:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 21:26:34.642401 2018] [mpm_winnt:notice] [pid 2940:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 21:26:34.642401 2018] [core:notice] [pid 2940:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 21:26:34.643401 2018] [mpm_winnt:notice] [pid 2940:tid 416] AH00418: Parent: Created child process 1952
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 21:26:35.090401 2018] [ssl:warn] [pid 1952:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:26:35.189401 2018] [ssl:warn] [pid 1952:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:26:35.217401 2018] [mpm_winnt:notice] [pid 1952:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:26:39.722401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:26:39.726401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:26:40.865401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:26:40.869401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:26:41.338401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:26:41.342401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:26:41.545401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:26:41.549401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5023] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:27:06.872401 2018] [php7:error] [pid 1952:tid 1524] [client 127.0.0.1:5049] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:27:06.876401 2018] [php7:error] [pid 1952:tid 1524] [client 127.0.0.1:5049] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:28:26.511401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5073] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:28:26.515401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5073] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:28:27.344401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5073] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:28:27.348401 2018] [php7:error] [pid 1952:tid 1548] [client 127.0.0.1:5073] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:04.823401 2018] [php7:error] [pid 1952:tid 1576] [client 127.0.0.1:5076] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:04.827401 2018] [php7:error] [pid 1952:tid 1576] [client 127.0.0.1:5076] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:06.019401 2018] [php7:error] [pid 1952:tid 1576] [client 127.0.0.1:5076] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:06.023401 2018] [php7:error] [pid 1952:tid 1576] [client 127.0.0.1:5076] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:10.139401 2018] [ssl:warn] [pid 800:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:29:10.284401 2018] [core:warn] [pid 800:tid 416] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Jun 26 21:29:10.287401 2018] [ssl:warn] [pid 800:tid 416] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:29:10.314401 2018] [mpm_winnt:notice] [pid 800:tid 416] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Tue Jun 26 21:29:10.314401 2018] [mpm_winnt:notice] [pid 800:tid 416] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Tue Jun 26 21:29:10.314401 2018] [core:notice] [pid 800:tid 416] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Jun 26 21:29:10.316401 2018] [mpm_winnt:notice] [pid 800:tid 416] AH00418: Parent: Created child process 5072
AH00548: NameVirtualHost has no effect and will be removed in the next release C:/xampp/apache/conf/extra/httpd-vhosts.conf:20
[Tue Jun 26 21:29:10.769401 2018] [ssl:warn] [pid 5072:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:29:10.860401 2018] [ssl:warn] [pid 5072:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 26 21:29:10.887401 2018] [mpm_winnt:notice] [pid 5072:tid 288] AH00354: Child: Starting 150 worker threads.
[Tue Jun 26 21:29:13.727401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:13.731401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:14.602401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:14.606401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:14.985401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:14.989401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:15.218401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:15.223401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:15.419401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:15.423401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:15.618401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:15.622401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:15.859401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:15.863401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:19.334401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:19.338401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:29:23.578401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:29:23.583401 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5079] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:30:46.657401 2018] [php7:error] [pid 5072:tid 1568] [client 127.0.0.1:5082] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:30:46.662401 2018] [php7:error] [pid 5072:tid 1568] [client 127.0.0.1:5082] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:30:47.371401 2018] [php7:error] [pid 5072:tid 1568] [client 127.0.0.1:5082] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:30:47.375401 2018] [php7:error] [pid 5072:tid 1568] [client 127.0.0.1:5082] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:39:55.731001 2018] [php7:error] [pid 5072:tid 1568] [client 127.0.0.1:5144] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:39:55.934001 2018] [php7:error] [pid 5072:tid 1568] [client 127.0.0.1:5144] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:40:09.096001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5148] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:40:09.101001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5148] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:40:11.924001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5148] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:40:11.929001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5148] PHP Fatal error:  Uncaught Error: Class 'Controller' not found in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php:174\nStack trace:\n#0 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php(92): ExceptionRenderer->_getController(Object(FatalErrorException))\n#1 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException))\n#2 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(274): ErrorHandler::handleException(Object(FatalErrorException))\n#3 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ErrorHandler.php(213): ErrorHandler::handleFatalError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30)\n#4 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(933): ErrorHandler::handleError(64, 'Cannot use 'Obj...', 'C:\\\\xampp\\\\htdocs...', 30, Array)\n#5 C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\App.php(906): App::_checkFatalError()\n#6 [internal function]: App::shutdown()\n#7 {main}\n  thrown in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Error\\ExceptionRenderer.php on line 174
[Tue Jun 26 21:41:09.453001 2018] [php7:error] [pid 5072:tid 1556] [client 127.0.0.1:5151] PHP Fatal error:  Class 'AppController' not found in C:\\xampp\\htdocs\\doctruyen\\app\\Controller\\UsersController.php on line 3
[Tue Jun 26 21:41:09.460001 2018] [php7:error] [pid 5072:tid 1556] [client 127.0.0.1:5151] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:42:58.391001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5154] PHP Fatal error:  Class 'AppController' not found in C:\\xampp\\htdocs\\doctruyen\\app\\Controller\\UsersController.php on line 3
[Tue Jun 26 21:42:58.398001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5154] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:42:59.263001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5154] PHP Fatal error:  Class 'AppController' not found in C:\\xampp\\htdocs\\doctruyen\\app\\Controller\\UsersController.php on line 3
[Tue Jun 26 21:42:59.271001 2018] [php7:error] [pid 5072:tid 1572] [client 127.0.0.1:5154] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:43:37.742001 2018] [php7:error] [pid 5072:tid 1552] [client 127.0.0.1:5157] PHP Fatal error:  Class 'AppController' not found in C:\\xampp\\htdocs\\doctruyen\\app\\Controller\\UsersController.php on line 3
[Tue Jun 26 21:43:37.749001 2018] [php7:error] [pid 5072:tid 1552] [client 127.0.0.1:5157] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
[Tue Jun 26 21:44:53.397001 2018] [php7:error] [pid 5072:tid 1552] [client 127.0.0.1:5162] PHP Fatal error:  Class 'AppController' not found in C:\\xampp\\htdocs\\doctruyen\\app\\Controller\\UsersController.php on line 3
[Tue Jun 26 21:44:53.404001 2018] [php7:error] [pid 5072:tid 1552] [client 127.0.0.1:5162] PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in C:\\xampp\\htdocs\\doctruyen\\lib\\Cake\\Core\\Object.php on line 30
